version: '3.9'

services:
  taiwan_tourguide:
    image: taiwan_tourguide:latest
    container_name: taiwan_tourguide
    command: 'sleep infinity'
    build:
      context: .
      args:
        NVM_VER: 0.39.1
        PNPM_VERSION: 7.6.0
        NODE_VER: 16.16.0
      dockerfile: ./Dockerfile
    privileged: true
    ports:
      - 3000:3000
    volumes:
      - ./:/home/ec2-user/workspace/
      - /home/ec2-user/.ssh:/home/ec2-user/.ssh
    stdin_open: true
